# Generated by Django 3.1.14 on 2025-03-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_tag_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='post_comments', to='blog.Comment', verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(db_index=True, verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Тег'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-published_at', 'title'], name='blog_post_publish_cdb0da_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='blog_post_slug_cdb902_idx'),
        ),
    ]
