# Generated by Django 5.1.7 on 2025-03-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_tag_options_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='Тег'),
        ),
    ]
