# Generated by Django 5.1.7 on 2025-03-15 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_tag_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['published_at'], 'verbose_name': 'комментарий'},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_publish_cdb0da_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_slug_cdb902_idx',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.post', verbose_name='Пост'),
        ),
    ]
